name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: Building web app
        uses: azure/appservice-build@v2
        with:
          source-directory: '/src/JobBoard/JobBoard.Web/'

      - name: Deploying web app to Azure
        uses: azure/webapps-deploy@v1
        with:
          app-name: 'JobBoardWeb20200923084251'
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}

